before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - "rake db:migrate"

rvm:
  - 2.0.0
  - 2.1.1

branches:
  only:
    - master

notifications:
  recipients:
    - ls@lucianosousa.net
    - rafael@tauil.com.br
    - rodrigopqn@gmail.com

addons:
  postgresql: "9.3"

