before_script:
  - "mysql -e 'create database startrack_test;' >/dev/null"
  - "rake db:migrate"

rvm:
  - 1.9.2
  - 1.9.3

branches:
  only:
    - master

notifications:
  recipients:
    - ls@lucianosousa.net
    - rafael@tauil.com.br
    - rodrigopqn@gmail.com

