development:
  adapter: postgresql
  encoding: unicode
  database: startrack_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: startrack_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: startrack_production
  pool: 5
  username: root
  password:
  host: localhost

